CREATE TABLE SUBSCRIPTION (
  ID BIGSERIAL PRIMARY KEY,
  CHAT_ID VARCHAR NOT NULL,
  REPOSITORY_NAME VARCHAR NOT NULL
);

CREATE TABLE REPOSITORY (
  ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR NOT NULL,
  VERSION VARCHAR
);